name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Specify a lower-bound SDK constraint

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1

  # Other dependencies (for Google sign-in, toast, local storage, etc.)
  google_sign_in: ^6.1.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  cached_network_image: ^3.2.1
  intl: ^0.19.0

  # Stick to material_color_utilities version required by flutter_test
  material_color_utilities: 0.11.1 

  # Other updated dependencies
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
