// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJau8VaMwk7fAMczRxEXCRIykPDUpq0Mk',
    appId: '1:189013248969:web:29e61431187b2a92227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    authDomain: 'facebookclone-23tech.firebaseapp.com',
    storageBucket: 'facebookclone-23tech.appspot.com',
    measurementId: 'G-KYHSYEL73V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uHu3hdBN4cGm6oZGWXQVvZzRUj8tjeQ',
    appId: '1:189013248969:android:f54503c43efb9819227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    storageBucket: 'facebookclone-23tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8p5rqo3yIPes4FtV2xGtvHcjRL5TNjtw',
    appId: '1:189013248969:ios:1d59ad88c020d45e227618',
    messagingSenderId: '189013248969',
    projectId: 'facebookclone-23tech',
    storageBucket: 'facebookclone-23tech.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
